name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Authenticates packages to push to GPR
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # SDK Version to use.
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_TOKEN}} # Note, create a secret with this name in Settings
    - run: dotnet build --configuration Release
    - run: dotnet test
    - name: Create the package
      run: dotnet pack --configuration Release AlloUI/AlloUI.csproj
    - name: Publish the package to Azure Artifacts
      run: dotnet nuget push AlloUI/bin/Release/*.nupkg --api-key ${{secrets.NUGET_API_TOKEN}} --source https://api.nuget.org/v3/index.json
